# Generated by Django 5.2.15 on 2026-06-23 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('scholar_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('hostel_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OutpassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpass_requests', to='outpass_app.student')),
            ],
        ),
    ]
