# Generated by Django 5.2.15 on 2026-06-23 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpassrequest',
            name='date',
        ),
        migrations.AddField(
            model_name='outpassrequest',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outpassrequest',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
