# Generated by Django 5.2.15 on 2026-06-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_app', '0002_remove_outpassrequest_date_outpassrequest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpassrequest',
            name='destination',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='outpassrequest',
            name='purpose',
            field=models.CharField(default='', max_length=200),
        ),
    ]
