# Generated by Django 5.2.15 on 2026-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_app', '0003_outpassrequest_destination_outpassrequest_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
