# Generated by Django 5.2.15 on 2026-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_app', '0004_student_destination_student_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpassrequest',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
